//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BirthdayService.ServiceReferenceWeb {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceWeb.WebBirthdaySoap")]
    public interface WebBirthdaySoap {
        
        // CODEGEN: Контракт генерации сообщений с именем name из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddData", ReplyAction="*")]
        BirthdayService.ServiceReferenceWeb.AddDataResponse AddData(BirthdayService.ServiceReferenceWeb.AddDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddData", ReplyAction="*")]
        System.Threading.Tasks.Task<BirthdayService.ServiceReferenceWeb.AddDataResponse> AddDataAsync(BirthdayService.ServiceReferenceWeb.AddDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddData", Namespace="http://tempuri.org/", Order=0)]
        public BirthdayService.ServiceReferenceWeb.AddDataRequestBody Body;
        
        public AddDataRequest() {
        }
        
        public AddDataRequest(BirthdayService.ServiceReferenceWeb.AddDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string date;
        
        public AddDataRequestBody() {
        }
        
        public AddDataRequestBody(string name, string date) {
            this.name = name;
            this.date = date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public BirthdayService.ServiceReferenceWeb.AddDataResponseBody Body;
        
        public AddDataResponse() {
        }
        
        public AddDataResponse(BirthdayService.ServiceReferenceWeb.AddDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddDataResult;
        
        public AddDataResponseBody() {
        }
        
        public AddDataResponseBody(string AddDataResult) {
            this.AddDataResult = AddDataResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebBirthdaySoapChannel : BirthdayService.ServiceReferenceWeb.WebBirthdaySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebBirthdaySoapClient : System.ServiceModel.ClientBase<BirthdayService.ServiceReferenceWeb.WebBirthdaySoap>, BirthdayService.ServiceReferenceWeb.WebBirthdaySoap {
        
        public WebBirthdaySoapClient() {
        }
        
        public WebBirthdaySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebBirthdaySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebBirthdaySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebBirthdaySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BirthdayService.ServiceReferenceWeb.AddDataResponse BirthdayService.ServiceReferenceWeb.WebBirthdaySoap.AddData(BirthdayService.ServiceReferenceWeb.AddDataRequest request) {
            return base.Channel.AddData(request);
        }
        
        public string AddData(string name, string date) {
            BirthdayService.ServiceReferenceWeb.AddDataRequest inValue = new BirthdayService.ServiceReferenceWeb.AddDataRequest();
            inValue.Body = new BirthdayService.ServiceReferenceWeb.AddDataRequestBody();
            inValue.Body.name = name;
            inValue.Body.date = date;
            BirthdayService.ServiceReferenceWeb.AddDataResponse retVal = ((BirthdayService.ServiceReferenceWeb.WebBirthdaySoap)(this)).AddData(inValue);
            return retVal.Body.AddDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BirthdayService.ServiceReferenceWeb.AddDataResponse> BirthdayService.ServiceReferenceWeb.WebBirthdaySoap.AddDataAsync(BirthdayService.ServiceReferenceWeb.AddDataRequest request) {
            return base.Channel.AddDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<BirthdayService.ServiceReferenceWeb.AddDataResponse> AddDataAsync(string name, string date) {
            BirthdayService.ServiceReferenceWeb.AddDataRequest inValue = new BirthdayService.ServiceReferenceWeb.AddDataRequest();
            inValue.Body = new BirthdayService.ServiceReferenceWeb.AddDataRequestBody();
            inValue.Body.name = name;
            inValue.Body.date = date;
            return ((BirthdayService.ServiceReferenceWeb.WebBirthdaySoap)(this)).AddDataAsync(inValue);
        }
    }
}
